tags:
  [
    {
      frame: "tag_0",
      id: 0,
      corners: [
        [-0.4318,0.4318,0.0],
        [0.4318,0.4318,0.0],
        [0.4318,-0.4318,0.0]
      ]
    }
  ]
bundles:
  [
  ]

# Marker corner order:
# 1          2
#  HD########
#  #ID#  ####
#  ##  ##  ##
#  ####  ####
#  ##########
# 4          3
